'use client';

import { useRef } from 'react';
import { Container } from '@/components/ui/Container';
import { PortableText } from '@portabletext/react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function PhilosophySection({ bio }: { bio: any }) {
  const sectionRef = useRef<HTMLElement>(null);
  const textContainerRef = useRef<HTMLDivElement>(null);
  const lineRef = useRef<HTMLDivElement>(null);

  useGSAP(() => {
    if (!sectionRef.current || !textContainerRef.current) return;
    
    // Select all paragraphs generated by PortableText
    const paragraphs = textContainerRef.current.querySelectorAll('.prose p');
    
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: sectionRef.current,
        start: 'top 70%',
        end: 'top 30%',
        toggleActions: 'play none none reverse',
      }
    });

    // Label fade in
    tl.fromTo('.phil-label',
      { opacity: 0, y: 20 },
      { opacity: 1, y: 0, duration: 0.8, ease: 'power3.out' }
    );

    // High-end typographic reveal for paragraphs
    if (paragraphs.length > 0) {
      tl.fromTo(paragraphs,
        { 
          opacity: 0, 
          y: 60,
          rotationX: 10,
          transformOrigin: '0% 50% -50'
        },
        {
          opacity: 1,
          y: 0,
          rotationX: 0,
          duration: 1.2,
          stagger: 0.2,
          ease: 'power4.out',
        },
        "-=0.4"
      );
    }

    // Expanding structural line
    if (lineRef.current) {
      tl.fromTo(lineRef.current,
        { scaleX: 0, transformOrigin: 'left center', opacity: 0 },
        { scaleX: 1, opacity: 1, duration: 1, ease: 'power4.out' },
        "-=0.8"
      );
    }

    // Scroll-linked parallax for the entire block
    gsap.to(textContainerRef.current, {
      y: '-10%',
      ease: 'none',
      scrollTrigger: {
        trigger: sectionRef.current,
        start: 'top bottom',
        end: 'bottom top',
        scrub: true,
      }
    });

  }, { scope: sectionRef });

  const displayBio = bio || [
    {
      _type: 'block',
      _key: 'fallback_1',
      style: 'normal',
      markDefs: [],
      children: [
        {
          _type: 'span',
          _key: 'span_1',
          text: 'Great engineering isn\'t defined by the final product, but by the discipline behind it. My work combines mechanical engineering and applied physics to understand how systems behave under real constraints. ',
          marks: []
        }
      ]
    },
    {
      _type: 'block',
      _key: 'fallback_2',
      style: 'normal',
      markDefs: [],
      children: [
        {
          _type: 'span',
          _key: 'span_2',
          text: 'Whether developing aerospace components or optimizing mechanical designs, every project follows the same process: design, test, analyze, refine. Good engineering begins with understanding the physics.',
          marks: []
        }
      ]
    }
  ];

  return (
    <section ref={sectionRef} className="w-full bg-background text-foreground py-[25vh] md:py-[35vh] relative z-10 overflow-hidden" aria-label="Engineering Philosophy">
      <Container variant="reading">
        <div ref={textContainerRef} className="max-w-4xl mx-auto flex flex-col gap-10 md:gap-16 text-left">
          
          <div className="flex items-center gap-4 phil-label opacity-0">
            <div className="w-2 h-2 rounded-full bg-accent animate-pulse" />
            <h2 className="font-mono text-[10px] md:text-xs uppercase tracking-[0.3em] text-text-secondary">
              Engineering Philosophy
            </h2>
          </div>
          
          {/* 
            Perfect Typography:
            - clamp() for fluid, massive scale
            - tracking-tighter for premium editorial look
            - leading-none or extremely tight line-height
            - text-balance to prevent orphans
          */}
          <div className="prose 
            prose-p:text-[clamp(2rem,6vw,5rem)] 
            prose-p:leading-[1.05] 
            prose-p:font-bold 
            prose-p:tracking-tighter 
            prose-p:text-text-primary 
            prose-p:text-balance
            prose-strong:text-accent
            prose-strong:font-bold
            dark:prose-invert 
            max-w-none 
            perspective-[1000px]
          ">
            <PortableText value={displayBio} />
          </div>
          
          {/* Structural accent line */}
          <div ref={lineRef} className="w-16 md:w-32 h-[2px] bg-accent mt-4 md:mt-8 opacity-0" />
          
        </div>
      </Container>
    </section>
  );
}