'use client';

import { useRef } from 'react';
import { Container } from '@/components/ui/Container';
import { PortableText } from '@portabletext/react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import Image from 'next/image';

export function PhilosophySection({ bio }: { bio: any }) {
  const sectionRef = useRef<HTMLElement>(null);
  const portraitRef = useRef<HTMLDivElement>(null);
  const frameRef = useRef<HTMLDivElement>(null);
  const textContainerRef = useRef<HTMLDivElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);
  const lineRef = useRef<HTMLDivElement>(null);
  const manifestoRef = useRef<HTMLParagraphElement>(null);

  useGSAP(() => {
    if (!sectionRef.current) return;
    
    // Select all paragraphs generated by PortableText
    const paragraphs = textContainerRef.current?.querySelectorAll('.prose p');
    
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: sectionRef.current,
        start: 'top 80%',
        toggleActions: 'play none none reverse',
      }
    });

    // 1. Portrait fade, scale, and heavy translate (deliberate motion)
    tl.fromTo(portraitRef.current,
      { opacity: 0, x: -80, scale: 0.97 },
      { opacity: 1, x: 0, scale: 1, duration: 1.4, ease: 'power3.out' },
      0
    );

    // 2. Editorial Frame & Crop marks reveal
    tl.fromTo(frameRef.current,
      { opacity: 0 },
      { opacity: 1, duration: 0.6, ease: 'power3.out' },
      0.3
    );

    // 3. Section heading reveal
    tl.fromTo(headingRef.current,
      { opacity: 0, y: 15 },
      { opacity: 1, y: 0, duration: 0.8, ease: 'power3.out' },
      0.5
    );

    // 4. Divider grows from left to right
    tl.fromTo(lineRef.current,
      { scaleX: 0, transformOrigin: 'left' },
      { scaleX: 1, duration: 1.0, ease: 'power4.out' },
      0.65
    );

    // 5. Manifesto appears
    tl.fromTo(manifestoRef.current,
      { opacity: 0, y: 15 },
      { opacity: 1, y: 0, duration: 1.0, ease: 'power3.out' },
      0.8
    );

    // 6. Body paragraphs reveal with subtle stagger
    if (paragraphs && paragraphs.length > 0) {
      tl.fromTo(paragraphs,
        { opacity: 0, y: 15 },
        {
          opacity: 1,
          y: 0,
          duration: 1.0,
          stagger: 0.05,
          ease: 'power3.out',
        },
        0.95
      );
    }

    // 7. Idle floating motion (kicks in after entrance)
    gsap.to(portraitRef.current, {
      y: '+=2',
      rotation: 0.2,
      duration: 3,
      yoyo: true,
      repeat: -1,
      ease: 'sine.inOut',
      delay: 1.5 // Start after entrance finishes
    });

  }, { scope: sectionRef });

  const displayBio = bio || [
    {
      _type: 'block',
      _key: 'fallback_1',
      style: 'normal',
      markDefs: [],
      children: [
        {
          _type: 'span',
          _key: 'span_1',
          text: 'Great engineering isn\'t defined by the final product, but by the discipline behind it. My work combines mechanical engineering and applied physics to understand how systems behave under real constraints.',
          marks: []
        }
      ]
    },
    {
      _type: 'block',
      _key: 'fallback_2',
      style: 'normal',
      markDefs: [],
      children: [
        {
          _type: 'span',
          _key: 'span_2',
          text: 'Whether developing aerospace components or optimizing mechanical designs, every project follows the same process: design, test, analyze, refine. Good engineering begins with understanding the physics.',
          marks: []
        }
      ]
    }
  ];

  return (
    <section id="about" ref={sectionRef} className="w-full bg-surface-paper text-text-primary py-32 flex items-center relative z-10 overflow-hidden" aria-label="Engineering Philosophy">
      <Container variant="hero" className="relative z-10">
        
        {/* Unified Editorial Grid Composition */}
        <div className="grid grid-cols-1 md:grid-cols-[5fr_7fr] gap-10 md:gap-[120px] items-start">
          
          {/* Portrait Column - Reduced slightly (8%) for breathing room */}
          <div className="relative w-full max-w-[280px] md:max-w-none md:w-[92%] aspect-[4/5] mx-auto md:mx-0">
            {/* The Image Itself */}
            <div ref={portraitRef} className="absolute inset-0 w-full h-full shadow-elevation-low overflow-hidden bg-surface-canvas">
              <div className="absolute inset-0 bg-surface-canvas" />
              <Image 
                src="/images/placeholders/vivan_portrait_1783865996256.png" 
                alt="Vivan Nagrath" 
                fill 
                sizes="(max-width: 768px) 100vw, 40vw"
                className="object-cover object-top opacity-90 mix-blend-multiply filter contrast-125 saturate-50 sepia-[0.2]" 
              />
              
              {/* Very subtle editorial vignette */}
              <div className="absolute inset-0 opacity-15 pointer-events-none mix-blend-multiply" style={{ background: 'radial-gradient(circle at center, transparent 40%, rgba(0,0,0,0.15) 100%)' }} />
              
              {/* 1px Graphite Frame */}
              <div className="absolute inset-0 border border-theme-text-primary/20 pointer-events-none" />
            </div>

            {/* Editorial Crop Marks & Metadata Frame (Outer) */}
            <div ref={frameRef} className="absolute inset-0 pointer-events-none">
              {/* Top Left Crop */}
              <div className="absolute -top-3 -left-3 w-4 h-4 border-t border-l border-theme-text-primary/15" style={{ borderWidth: '0.5px' }} />
              {/* Bottom Right Crop */}
              <div className="absolute -bottom-3 -right-3 w-4 h-4 border-b border-r border-theme-text-primary/15" style={{ borderWidth: '0.5px' }} />
              {/* Lens Metadata Removed per request */}
            </div>
          </div>

          {/* Typography Column - Strict Vertical Rhythm & Measure */}
          {/* Eye-level alignment using a top margin push on desktop to sit slightly below the absolute top of the portrait */}
          <div ref={textContainerRef} className="w-full flex flex-col text-left relative md:mt-[12%] max-w-[65ch]">
            
            {/* Section Heading */}
            <h2 ref={headingRef} className="font-mono text-[11px] md:text-[12px] font-medium uppercase tracking-[0.2em] text-text-secondary leading-none">
              Engineering Philosophy
            </h2>
            
            {/* Rhythm: 24px */}
            <div className="h-[24px] w-full" />
            
            {/* Structural Divider */}
            <div ref={lineRef} className="w-full max-w-[200px] h-[1px] bg-theme-text-primary/20" />
            
            {/* Rhythm: 32px */}
            <div className="h-[32px] w-full" />
            
            {/* Manifesto Sentence */}
            <p ref={manifestoRef} className="font-serif text-heading-m md:text-heading-l text-text-primary leading-[1.3] font-medium tracking-tight text-balance">
              Every system begins with first principles.
            </p>
            
            {/* Rhythm: 40px */}
            <div className="h-[40px] w-full" />
            
            {/* Body Copy Measure */}
            <div className="prose 
              prose-p:text-body-l 
              prose-p:font-sans
              prose-p:leading-[1.65] 
              prose-p:text-text-secondary 
              prose-strong:text-text-primary
              prose-strong:font-medium
              max-w-none 
            ">
              {Array.isArray(displayBio) && <PortableText value={displayBio} />}
            </div>
            
          </div>
        </div>
      </Container>
    </section>
  );
}